"""
Build MMDetection config files from user settings
"""
import os
import sys
from pathlib import Path

# Add parent directory to path for imports
sys.path.append(str(Path(__file__).parent.parent))
from configs.model_configs import get_model_config

# Import Albumentations wrapper
import albumentations as A


def build_mmdet_config(
    model_size,
    data_root,
    class_names,
    num_classes,
    img_size,
    epochs,
    batch_size=None,
    lr=0.01,
    momentum=0.937,
    weight_decay=0.0005,
    warmup_epochs=3,
    work_dir=None,
    mosaic_prob=1.0,
    mixup_prob=0.0,  # Changed: YOLOv11n doesn't use mixup
    hsv_h=0.015,
    hsv_s=0.7,
    hsv_v=0.4,
    degrees=0.0,  # Changed: YOLOv11n doesn't use rotation
    translate=0.1,
    scale=0.5,
    shear=0.0,  # Changed: YOLOv11n doesn't use shear
    flipud=0.0,
    fliplr=0.5
):
    """
    Build MMDetection config file content

    Args:
        model_size: 'nano', 'small', 'medium', or 'large'
        data_root: Path to COCO format dataset
        class_names: List of class names
        num_classes: Number of classes
        img_size: Image size (width, height)
        epochs: Number of training epochs
        batch_size: Batch size (if None, uses default from model config)
        lr: Learning rate
        momentum: SGD momentum
        weight_decay: Weight decay
        warmup_epochs: Number of warmup epochs
        work_dir: Working directory for outputs

    Returns:
        str: Config file content
    """

    model_config = get_model_config(model_size)

    if batch_size is None:
        batch_size = model_config['batch_size']

    if work_dir is None:
        work_dir = f'./work_dirs/solov2_{model_size}'

    # Convert class names to tuple format
    classes_str = str(tuple(class_names))

    config_content = f'''# SOLOv2 {model_size.upper()} Configuration
# Auto-generated by SOLOv2 Trainer

# Base configs
_base_ = [
    '/home/farshid/anaconda3/envs/rgbt/lib/python3.11/site-packages/mmdet/.mim/configs/_base_/schedules/schedule_1x.py',
    '/home/farshid/anaconda3/envs/rgbt/lib/python3.11/site-packages/mmdet/.mim/configs/_base_/default_runtime.py'
]

# Custom transforms
custom_imports = dict(
    imports=['utils.mosaic_transform'],
    allow_failed_imports=False)

# Dataset settings
dataset_type = 'CocoDataset'
data_root = '{data_root}'
classes = {classes_str}
num_classes = {num_classes}

# Model settings - {model_size.upper()} variant
model = dict(
    type='SOLOv2',
    data_preprocessor=dict(
        type='DetDataPreprocessor',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        bgr_to_rgb=True,
        pad_mask=True,
        pad_size_divisor=32),
    backbone=dict(
        type='{model_config['backbone']['type']}',
        depth={model_config['backbone']['depth']},
        num_stages={model_config['backbone']['num_stages']},
        out_indices={model_config['backbone']['out_indices']},
        frozen_stages={model_config['backbone']['frozen_stages']},
        init_cfg=dict(type='Pretrained', checkpoint='{model_config['backbone']['init_cfg']['checkpoint']}'),
        style='{model_config['backbone']['style']}'),
    neck=dict(
        type='{model_config['neck']['type']}',
        in_channels={model_config['neck']['in_channels']},
        out_channels={model_config['neck']['out_channels']},
        start_level={model_config['neck']['start_level']},
        num_outs={model_config['neck']['num_outs']}),
    mask_head=dict(
        type='SOLOV2Head',
        num_classes=num_classes,
        in_channels={model_config['mask_head']['in_channels']},
        feat_channels={model_config['mask_head']['feat_channels']},
        stacked_convs={model_config['mask_head']['stacked_convs']},
        strides=[8, 8, 16, 32, 32],
        scale_ranges=((1, 96), (48, 192), (96, 384), (192, 768), (384, 2048)),
        pos_scale=0.2,
        num_grids=[40, 36, 24, 16, 12],
        cls_down_index=0,
        mask_feature_head=dict(
            feat_channels={model_config['mask_head']['mask_feature_head']['feat_channels']},
            start_level={model_config['mask_head']['mask_feature_head']['start_level']},
            end_level={model_config['mask_head']['mask_feature_head']['end_level']},
            out_channels={model_config['mask_head']['mask_feature_head']['out_channels']},
            mask_stride={model_config['mask_head']['mask_feature_head']['mask_stride']},
            norm_cfg=dict(type='GN', num_groups=32, requires_grad=True)),
        loss_mask=dict(type='DiceLoss', use_sigmoid=True, loss_weight=3.0),
        loss_cls=dict(
            type='FocalLoss',
            use_sigmoid=True,
            gamma=2.0,
            alpha=0.25,
            loss_weight=1.0)),
    test_cfg=dict(
        nms_pre=500,
        score_thr=0.1,
        mask_thr=0.5,
        filter_thr=0.05,
        kernel='gaussian',
        sigma=2.0,
        max_per_img=100))

# Data pipeline
img_scale = ({img_size[0]}, {img_size[1]})
backend_args = None

train_pipeline = [
    dict(type='LoadImageFromFile', backend_args=backend_args),
    dict(type='LoadAnnotations', with_bbox=True, with_mask=True),
    # Mosaic augmentation (custom implementation with mask support)
    dict(
        type='MosaicWithMasks',
        img_scale=img_scale,
        center_ratio_range=(0.5, 1.5),
        pad_val=114,
        prob={mosaic_prob}
    ),
    # Albumentations augmentations (using MMDetection's official Albu wrapper)
    dict(
        type='Albu',
        transforms=[
            # HSV color augmentation
            dict(
                type='HueSaturationValue',
                hue_shift_limit=int({hsv_h} * 179),
                sat_shift_limit=int({hsv_s} * 255),
                val_shift_limit=int({hsv_v} * 255),
                p=0.9
            ),
            # Full Ultralytics-style geometric transforms
            # With filter_lost_elements=True, masks properly sync when objects are cropped
            dict(
                type='Affine',
                rotate=(-{degrees}, {degrees}),  # Full rotation range (default ±10°)
                translate_percent={{'x': (-{translate}, {translate}), 'y': (-{translate}, {translate})}},  # Translation (default ±10%)
                scale=(1.0 - {scale}, 1.0 + {scale}),  # Scale range (default 0.5-1.5)
                shear=(-{shear}, {shear}),  # Shear (default ±2°)
                border_mode=0,  # cv2.BORDER_CONSTANT
                value=114,  # Gray padding value
                p=0.8
            ),
            # Random brightness and contrast
            dict(
                type='RandomBrightnessContrast',
                brightness_limit=0.2,
                contrast_limit=0.2,
                p=0.5
            ),
            # Flips
            dict(type='HorizontalFlip', p={fliplr}),
            dict(type='VerticalFlip', p={flipud}),
        ],
        bbox_params=dict(
            type='BboxParams',
            format='pascal_voc',
            label_fields=['gt_bboxes_labels', 'gt_ignore_flags'],  # Critical: include gt_ignore_flags for filtering
            min_visibility=0.0,
            min_area=0.0,
            filter_lost_elements=True  # Critical: sync masks with bboxes when objects are dropped
        ),
        keymap=dict(
            img='image',
            gt_bboxes='bboxes',
            gt_masks='masks'
        )
    ),
    # Resize to target size
    dict(
        type='Resize',
        scale=img_scale,
        keep_ratio=True),
    dict(type='PackDetInputs')
]

test_pipeline = [
    dict(type='LoadImageFromFile', backend_args=backend_args),
    dict(type='Resize', scale=img_scale, keep_ratio=True),
    dict(type='LoadAnnotations', with_bbox=True, with_mask=True),
    dict(
        type='PackDetInputs',
        meta_keys=('img_id', 'img_path', 'ori_shape', 'img_shape', 'scale_factor'))
]

# Base pipeline for loading data before Mosaic
pre_mosaic_pipeline = [
    dict(type='LoadImageFromFile', backend_args=backend_args),
    dict(type='LoadAnnotations', with_bbox=True, with_mask=True)
]

# Mosaic pipeline (applied after loading 4 images)
mosaic_pipeline = [
    dict(
        type='MosaicWithMasks',
        img_scale=img_scale,
        center_ratio_range=(0.5, 1.5),
        pad_val=114,
        prob={mosaic_prob}
    ),
    # MixUp augmentation (blends images with alpha compositing)
    dict(
        type='CachedMixUp',
        img_scale=img_scale,
        ratio_range=(0.8, 1.6),
        flip_ratio=0.5,
        pad_val=114,
        prob={mixup_prob}
    ),
    # Albumentations augmentations
    dict(
        type='Albu',
        transforms=[
            # HSV color augmentation
            dict(
                type='HueSaturationValue',
                hue_shift_limit=int({hsv_h} * 179),
                sat_shift_limit=int({hsv_s} * 255),
                val_shift_limit=int({hsv_v} * 255),
                p=0.9
            ),
            # Full Ultralytics-style geometric transforms
            dict(
                type='Affine',
                rotate=(-{degrees}, {degrees}),
                translate_percent={{'x': (-{translate}, {translate}), 'y': (-{translate}, {translate})}},
                scale=(1.0 - {scale}, 1.0 + {scale}),
                shear=(-{shear}, {shear}),
                border_mode=0,
                value=114,
                p=0.8
            ),
            # Random brightness and contrast
            dict(
                type='RandomBrightnessContrast',
                brightness_limit=0.2,
                contrast_limit=0.2,
                p=0.5
            ),
            # Flips
            dict(type='HorizontalFlip', p={fliplr}),
            dict(type='VerticalFlip', p={flipud}),
        ],
        bbox_params=dict(
            type='BboxParams',
            format='pascal_voc',
            label_fields=['gt_bboxes_labels', 'gt_ignore_flags'],  # Critical: include gt_ignore_flags for filtering
            min_visibility=0.0,
            min_area=0.0,
            filter_lost_elements=True
        ),
        keymap=dict(
            img='image',
            gt_bboxes='bboxes',
            gt_masks='masks'
        )
    ),
    dict(type='Resize', scale=img_scale, keep_ratio=True),
    dict(type='PackDetInputs')
]

# Dataloaders
train_dataloader = dict(
    batch_size={batch_size},
    num_workers=4,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=True),
    dataset=dict(
        type='MultiImageMixDataset',
        dataset=dict(
            type=dataset_type,
            data_root=data_root,
            ann_file='annotations/instances_train.json',
            data_prefix=dict(img='train/'),
            filter_cfg=dict(filter_empty_gt=False, min_size=32),
            pipeline=pre_mosaic_pipeline,
            backend_args=backend_args,
            metainfo=dict(classes=classes)),
        pipeline=mosaic_pipeline))

val_dataloader = dict(
    batch_size={batch_size},
    num_workers=4,  # Re-enabled with official Albu class
    persistent_workers=True,
    drop_last=False,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=dict(
        type=dataset_type,
        data_root=data_root,
        ann_file='annotations/instances_val.json',
        data_prefix=dict(img='val/'),
        test_mode=True,
        pipeline=test_pipeline,
        backend_args=backend_args,
        metainfo=dict(classes=classes)))

test_dataloader = val_dataloader

# Evaluators
val_evaluator = dict(
    type='CocoMetric',
    ann_file=data_root + 'annotations/instances_val.json',
    metric=['segm'],
    backend_args=backend_args)
test_evaluator = val_evaluator

# Training settings
max_epochs = {epochs}
train_cfg = dict(max_epochs=max_epochs, val_interval=10)

# Optimizer - CRITICAL: Use YOLO's AUTO learning rate formula!
# When optimizer='auto', YOLO uses: lr = 0.002 * 5 / (4 + num_classes)
# For {num_classes} classes: lr = 0.01 / (4 + {num_classes}) = {round(0.01 / (4 + num_classes), 6)}
actual_peak_lr = round(0.002 * 5 / (4 + {num_classes}), 6)  # YOLO's auto LR formula
optim_wrapper = dict(
    type='OptimWrapper',
    optimizer=dict(type='SGD', lr=actual_peak_lr, momentum={momentum}, weight_decay={weight_decay}),
    clip_grad=dict(max_norm=35, norm_type=2))

# Learning rate scheduler matching YOLO Nano's ACTUAL behavior from train36:
# Warmup: 7 epochs from 2% to 100% of peak (0.0002 -> 0.00137)
# Then: Cosine decay from epoch 8 to 150 down to 1.7% (0.000024)
param_scheduler = [
    dict(
        type='LinearLR',
        start_factor=0.02,  # Start at 2% (0.0002)
        by_epoch=True,
        begin=0,
        end=7),  # 7 epochs warmup (matches YOLO exactly)
    dict(
        type='CosineAnnealingLR',
        T_max=max_epochs - 7,
        eta_min=actual_peak_lr * 0.017,  # End at 1.7% of peak (matches YOLO)
        begin=7,
        end=max_epochs,
        by_epoch=True)
]

# Default hooks
default_hooks = dict(
    checkpoint=dict(
        type='CheckpointHook',
        interval=10,
        max_keep_ckpts=3,
        save_best='coco/segm_mAP',  # Save best model based on mask mAP
        rule='greater'),  # Higher mAP is better
    logger=dict(type='LoggerHook', interval=10))

# Visualizer with TensorBoard backend
vis_backends = [
    dict(type='LocalVisBackend'),
    dict(type='TensorboardVisBackend')
]
visualizer = dict(
    type='DetLocalVisualizer',
    vis_backends=vis_backends,
    name='visualizer')

# Auto-scale learning rate based on batch size (matches Ultralytics behavior)
auto_scale_lr = dict(
    enable=True,
    base_batch_size={batch_size}  # Base batch size for configured lr
)

# Runtime settings
work_dir = '{work_dir}'
'''

    return config_content
